<?php
return [
	'device_id' => 1,
	'token' => 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9zZGdhdGV3YXkuaGVyb2t1YXBwLmNvbVwvYXBpXC9kZXZpY2VcL3JlZnJlc2giLCJpYXQiOjE1ODk3MjA5MzMsImV4cCI6MTU4OTcyNTYzMCwibmJmIjoxNTg5NzIyMDMwLCJqdGkiOiJPNUowTlRqaTVuMExXZXdnIiwic3ViIjoxfQ.Osh1apPrFqLrznlxmSV53t_dJzbInwPKrBBgqlOuY6Y',
];